In [ ]:
from google.colab import drive
drive.mount('/content/drive')
!ls "/content/drive/My Drive/capston/new"

Mounted at /content/drive
ls: cannot access '/content/drive/My Drive/capston/new': No such file or directory

In [ ]:
import pandas as pd
df = pd.read_csv("/content/drive/My Drive/capstone/new/data.txt", sep="|", header=0)
identity = pd.read_csv("/content/drive/My Drive/capstone/new/identity.txt", sep="|", header=0)

In [ ]:
df.head()

,sa_finance1_cocode,sa_company_name,sa_finance1_year,sa_ann_rep_months,sa_fs_format,sa_total_income,sa_compensation_to_employees,sa_corporate_tax,sa_emp_compens_n_travel,sa_exp_total_taxes,sa_direct_taxes_incl_mat_n_def_tax,sa_pat,sa_total_assets,sa_cf_direct_taxes_paid_outflow,sa_no_of_employees
0,3,'K' STEAMSHIP AGENCIES PVT. LTD.,20010331,12,IGAAP,0.6842,0.1394,0.1072,0.1587,0.1115,0.1115,0.1351,3.7087,NaN,NaN
1,3,'K' STEAMSHIP AGENCIES PVT. LTD.,20020331,12,IGAAP,1.7645,0.1498,0.1293,0.2093,0.5950,0.1354,0.5437,3.2356,NaN,NaN
2,3,'K' STEAMSHIP AGENCIES PVT. LTD.,20030331,12,IGAAP,1.8660,0.2645,0.3463,0.3400,0.3463,0.3463,0.5478,5.1027,NaN,NaN
3,3,'K' STEAMSHIP AGENCIES PVT. LTD.,20040331,12,IGAAP,2.5436,0.3310,0.3777,0.4665,0.4065,0.4065,0.9130,6.9755,NaN,NaN
4,3,'K' STEAMSHIP AGENCIES PVT. LTD.,20110331,12,IGAAP,8.4020,1.3314,1.4226,1.4248,1.6893,1.6759,2.5095,13.2364,NaN,NaN

In [ ]:
identity.head()

,co_code,company_name,co_industry_type,co_industry_gp_code,co_industry_name
0,3,'K' STEAMSHIP AGENCIES PVT. LTD.,1.0,1.100000e+14,Diversified
1,11,20 MICRONS LTD.,1.0,1.010203e+14,Minerals
2,12,20TH CENTURY ENGG. LTD.,1.0,1.010415e+14,Business services & consultancy
3,13,GREENSTONE INVESTMENTS PVT. LTD.,2.0,1.020400e+14,Other fund based financial services
4,14,20TH CENTURY FINANCE CORPN. LTD. [MERGED],2.0,1.020315e+14,Other asset financing services

In [ ]:
df_excel = pd.read_excel("/content/drive/My Drive/capstone/BUYOUTINDIA.xlsx", sheet_name=0)

In [ ]:
df_excel.head()

  Transaction Date                                            Company  Column1
0       2017-11-22                   34 Cross Systems Private Limited        1
1       2015-10-24                  360 One Wam Limited (NSEI:360ONE)        1
2       2005-02-18         63 moons technologies limited (BSE:526881)        1
3       2020-06-12  91Streets Media Technologies/Ascent Health/API...        1
4       2010-06-01                                 9X Media Pvt. Ltd.        1

In [ ]:
df[df['sa_company_name'].str.lower().str.contains('aragen life sciences', na=False)]

,sa_finance1_cocode,sa_company_name,sa_finance1_year,sa_ann_rep_months,sa_fs_format,sa_total_income,sa_compensation_to_employees,sa_corporate_tax,sa_emp_compens_n_travel,sa_exp_total_taxes,sa_direct_taxes_incl_mat_n_def_tax,sa_pat,sa_total_assets,sa_cf_direct_taxes_paid_outflow,sa_no_of_employees
423045,285013,ARAGEN LIFE SCIENCES LTD.,20100331,12,IGAAP,51.1363,0.0703,0.3561,0.0703,0.3561,0.3561,7.3058,71.7086,1.3209,NaN
423046,285013,ARAGEN LIFE SCIENCES LTD.,20110331,12,IGAAP,56.8266,17.5263,0.2223,17.5263,0.2934,0.2934,6.3059,75.5776,2.9007,NaN
423047,285013,ARAGEN LIFE SCIENCES LTD.,20120331,12,IGAAP,64.6225,NaN,1.2102,NaN,1.2897,1.2897,12.9861,81.0544,NaN,NaN
423048,285013,ARAGEN LIFE SCIENCES LTD.,20130331,12,IGAAP,57.6683,0.2390,1.0440,0.2390,1.1727,1.1727,11.1517,86.5282,NaN,NaN
423049,285013,ARAGEN LIFE SCIENCES LTD.,20140331,12,IGAAP,68.6121,18.0713,1.6685,19.2431,2.8879,2.1290,15.7439,108.4980,NaN,1800.0
423050,285013,ARAGEN LIFE SCIENCES LTD.,20150331,12,IGAAP,75.6944,20.8680,2.9496,21.9568,3.6173,3.4860,14.8679,116.4760,NaN,2200.0
423051,285013,ARAGEN LIFE SCIENCES LTD.,20160331,12,INDAS,54.1390,15.7590,3.7137,16.4991,4.3180,4.2091,6.1174,114.0299,1.7696,2500.0
423052,285013,ARAGEN LIFE SCIENCES LTD.,20170331,12,INDAS,91.2380,21.7264,6.3042,22.5456,7.1066,6.3042,12.7480,130.5770,4.5234,NaN
423053,285013,ARAGEN LIFE SCIENCES LTD.,20180331,12,INDAS,93.3063,23.6030,4.7907,24.2613,7.2023,7.0115,10.8488,156.5364,3.9356,NaN
423054,285013,ARAGEN LIFE SCIENCES LTD.,20190331,12,INDAS,101.2729,23.5627,3.8789,24.3168,6.1127,5.7960,7.9737,161.8743,0.0000,NaN
423055,285013,ARAGEN LIFE SCIENCES LTD.,20200331,12,INDAS,110.3325,27.0045,6.1439,27.7509,12.3603,12.0819,11.4511,174.2351,4.5272,NaN
423056,285013,ARAGEN LIFE SCIENCES LTD.,20210331,12,INDAS,135.2812,31.4234,7.0295,31.8795,15.5002,15.0358,20.2795,206.4902,6.4086,NaN
423057,285013,ARAGEN LIFE SCIENCES LTD.,20220331,12,INDAS,164.5273,38.7844,8.1055,39.3537,8.4741,8.1055,27.6715,307.0425,9.0682,NaN
423058,285013,ARAGEN LIFE SCIENCES LTD.,20230331,12,INDAS,192.1241,44.8952,10.7864,45.7384,11.4486,10.7864,30.6073,296.2815,9.9627,NaN
423059,285013,ARAGEN LIFE SCIENCES LTD.,20240331,12,INDAS,179.5218,48.4217,8.2163,49.5157,8.7621,8.2163,22.7451,334.8419,8.8344,NaN

In [ ]:
df_excel[df_excel['Company'].str.lower().str.contains('aragen life sciences', na=False)]

   Transaction Date                       Company  Column1
51       2015-12-02  Aragen Life Sciences Limited        1

In [ ]:
identity[identity['company_name'].str.lower().str.contains('aragen life sciences', na=False)]

,co_code,company_name,co_industry_type,co_industry_gp_code,co_industry_name
28266,285013,ARAGEN LIFE SCIENCES LTD.,1.0,1.010415e+14,Business services & consultancy

In [ ]:
df = df.merge(identity[['company_name', 'co_industry_type','co_industry_gp_code', 'co_industry_name']],
              left_on="sa_company_name", right_on="company_name", how="left")
df

,sa_finance1_cocode,sa_company_name,sa_finance1_year,sa_ann_rep_months,sa_fs_format,sa_total_income,sa_compensation_to_employees,sa_corporate_tax,sa_emp_compens_n_travel,sa_exp_total_taxes,sa_direct_taxes_incl_mat_n_def_tax,sa_pat,sa_total_assets,sa_cf_direct_taxes_paid_outflow,sa_no_of_employees,company_name,co_industry_type,co_industry_gp_code,co_industry_name
0,3,'K' STEAMSHIP AGENCIES PVT. LTD.,20010331,12,IGAAP,0.6842,0.1394,0.1072,0.1587,0.1115,0.1115,0.1351,3.7087,NaN,NaN,'K' STEAMSHIP AGENCIES PVT. LTD.,1.0,1.100000e+14,Diversified
1,3,'K' STEAMSHIP AGENCIES PVT. LTD.,20020331,12,IGAAP,1.7645,0.1498,0.1293,0.2093,0.5950,0.1354,0.5437,3.2356,NaN,NaN,'K' STEAMSHIP AGENCIES PVT. LTD.,1.0,1.100000e+14,Diversified
2,3,'K' STEAMSHIP AGENCIES PVT. LTD.,20030331,12,IGAAP,1.8660,0.2645,0.3463,0.3400,0.3463,0.3463,0.5478,5.1027,NaN,NaN,'K' STEAMSHIP AGENCIES PVT. LTD.,1.0,1.100000e+14,Diversified
3,3,'K' STEAMSHIP AGENCIES PVT. LTD.,20040331,12,IGAAP,2.5436,0.3310,0.3777,0.4665,0.4065,0.4065,0.9130,6.9755,NaN,NaN,'K' STEAMSHIP AGENCIES PVT. LTD.,1.0,1.100000e+14,Diversified
4,3,'K' STEAMSHIP AGENCIES PVT. LTD.,20110331,12,IGAAP,8.4020,1.3314,1.4226,1.4248,1.6893,1.6759,2.5095,13.2364,NaN,NaN,'K' STEAMSHIP AGENCIES PVT. LTD.,1.0,1.100000e+14,Diversified
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
692163,720925,TRIJIT TECHNOLOGIES PVT. LTD.,20200331,12,IGAAP,0.0968,0.0256,0.0013,0.0256,0.0027,0.0013,0.0094,0.1479,NaN,NaN,TRIJIT TECHNOLOGIES PVT. LTD.,1.0,1.010408e+14,Computer software
692164,720925,TRIJIT TECHNOLOGIES PVT. LTD.,20210331,12,IGAAP,0.1250,0.0426,0.0014,0.0426,0.0027,0.0014,0.0110,0.1758,0.0014,NaN,TRIJIT TECHNOLOGIES PVT. LTD.,1.0,1.010408e+14,Computer software
692165,720925,TRIJIT TECHNOLOGIES PVT. LTD.,20220331,12,IGAAP,0.1062,0.0393,0.0013,0.0393,0.0026,0.0013,0.0328,0.2046,0.0013,NaN,TRIJIT TECHNOLOGIES PVT. LTD.,1.0,1.010408e+14,Computer software
692166,720925,TRIJIT TECHNOLOGIES PVT. LTD.,20230331,12,IGAAP,0.1349,0.0765,0.0012,0.0765,0.0024,0.0012,0.0097,0.2260,0.0012,NaN,TRIJIT TECHNOLOGIES PVT. LTD.,1.0,1.010408e+14,Computer software
692167,720925,TRIJIT TECHNOLOGIES PVT. LTD.,20240331,12,IGAAP,0.1988,0.1121,0.0024,0.1121,0.0036,0.0024,0.0060,0.1928,0.0024,NaN,TRIJIT TECHNOLOGIES PVT. LTD.,1.0,1.010408e+14,Computer software

In [ ]:
import pandas as pd
import re

# Step 1: Define a function to create a standardized match key
def extract_match_key(company_name):
    if pd.isna(company_name):
        return ""
    # Convert to lowercase
    company_name = company_name.lower()

    # Replace "pvt." (or "pvt") with "private" and "ltd." (or "ltd") with "limited"
    company_name = re.sub(r"\bpvt\.?\b", "private", company_name, flags=re.IGNORECASE)
    company_name = re.sub(r"\bltd\.?\b", "limited", company_name, flags=re.IGNORECASE)

    # Remove anything within brackets (non-greedy)
    company_name = re.sub(r"\s*\(.*?\)\s*", "", company_name)

    # Remove all non-alphanumeric characters
    company_name = re.sub(r"[^a-z0-9]", "", company_name)

    return company_name

# Assume df_excel and df are your two DataFrames
# Step 2: Apply the cleaning function to both dataframes
df_excel['Cleaned_Name'] = df_excel['Company'].apply(extract_match_key)
df['Cleaned_Name'] = df['sa_company_name'].apply(extract_match_key)

In [ ]:
import pandas as pd
import re
from google.colab import files

# Function to clean company names
def clean_company_name(name):
    if pd.isna(name):
        return ""
    name = name.lower()
    name = re.sub(r'\b(pvt\.?|ltd\.?|private|limited)\b', '', name)
    name = re.sub(r'\(.*?\)', '', name)  # Remove anything inside brackets
    name = re.sub(r'[^a-zA-Z0-9]', '', name)  # Remove all special characters
    return name.strip()

# Apply cleaning function to both datasets
df['Cleaned_Name'] = df['sa_company_name'].apply(clean_company_name)
df_excel['Cleaned_Name'] = df_excel['Company'].apply(clean_company_name)

# Merge with indicator to check matching
merged_check = df_excel.merge(df, on="Cleaned_Name", how="left", indicator=True)

# Extract unmatched companies from df_excel
unmatched_companies = merged_check[merged_check['_merge'] == 'left_only'][['Company']]
unmatched_companies.to_csv("unmatched_companies.csv", index=False)

# Perform full join and add PE_transaction & Transaction_Date columns
df_merged = df.merge(df_excel[['Cleaned_Name', 'Transaction Date']], on="Cleaned_Name", how="left")
df_merged['PE_transaction'] = df_merged['Transaction Date'].notna().astype(int)  # 1 if matched, else 0

# Save the merged dataset with PE transaction info
df_merged.to_csv("df_with_PE_transaction.csv", index=False)

# Download both files
files.download("unmatched_companies.csv")
files.download("df_with_PE_transaction.csv")

In [ ]:
df_matched = df_excel.merge(df, on='Cleaned_Name', how='left', indicator=True)

# Create a column indicating if the row was successfully merged
df_matched['Merged'] = df_matched['_merge'].apply(lambda x: 'Yes' if x == 'both' else 'No')

# Drop the unnecessary '_merge' column
df_matched.drop(columns=['_merge'], inplace=True)

# Count how many rows matched vs. did not match
match_counts = df_matched['Merged'].value_counts()
df_matched.to_csv("df_excel_merge_check.csv", index=False)
from google.colab import files
files.download("df_excel_merge_check.csv")
print(match_counts)

Merged
Yes    8032
No      426
Name: count, dtype: int64

In [ ]:
df['Cleaned_Name'] = df['sa_company_name'].str.lower().str.replace(r'\s+', '', regex=True)
df_excel['Cleaned_Name'] = df_excel['Company'].str.lower().str.replace(r'\s+', '', regex=True)

# Merge with indicator to check matching
merged_check = df_excel.merge(df, on="Cleaned_Name", how="left", indicator=True)

# Extract unmatched companies from df_excel
unmatched_companies = merged_check[merged_check['_merge'] == 'left_only'][['Company']]
unmatched_companies.to_csv("unmatched_companies.csv", index=False)

# Perform full join and add PE_transaction & Transaction_Date columns
df_merged = df.merge(df_excel[['Cleaned_Name', 'Transaction Date']], on="Cleaned_Name", how="left")
df_merged['PE_transaction'] = df_merged['Transaction Date'].notna().astype(int)  # 1 if matched, else 0

# Save the merged dataset with PE transaction info
df_merged.to_csv("df_with_PE_transaction.csv", index=False)

# Download both files
files.download("unmatched_companies.csv")
files.download("df_with_PE_transaction.csv")

In [ ]:

# Step 3: Generate match keys of varying lengths
df_excel['Match_Key_15'] = df_excel['Cleaned_Name'].str[:15]
df_excel['Match_Key_9'] = df_excel['Cleaned_Name'].str[:9]
df['Match_Key_15'] = df['Cleaned_Name'].str[:15]
df['Match_Key_9'] = df['Cleaned_Name'].str[:9]

# Step 4: Attempt to match using the match keys hierarchically
# Match using 15 characters
merged_15 = pd.merge(df,
                     df_excel[['Company', 'Transaction Date', 'Match_Key_15']],
                     left_on='Match_Key_15',
                     right_on='Match_Key_15',
                     how='inner')

# Remove matched rows from df_excel
unmatched_15 = df_excel[~df_excel['Match_Key_15'].isin(merged_15['Match_Key_15'])]

# Match using 9 characters from the unmatched data
merged_9 = pd.merge(df,
                    unmatched_15[['Company', 'Transaction Date', 'Match_Key_9']],
                    left_on='Match_Key_9',
                    right_on='Match_Key_9',
                    how='inner')

# Step 5: Combine all matched datasets
final_merged = pd.concat([merged_15, merged_9], ignore_index=True)

# final_merged now contains the combined results
print(final_merged)
df_matched.to_csv("df_excel_merge_check.csv", index=False)

KeyError: 'Cleaned_Name'

In [ ]:


# Merge the industry columns from identity to df based on company name
df = df.merge(identity[['company_name', 'co_industry_gp_code', 'co_industry_name']],
              left_on="sa_company_name", right_on="company_name", how="left")

# Read the Excel file (first sheet by default)


# Remove dashes from 'Transaction Date' column
df_excel['Transaction Date'] = df_excel['Transaction Date'].astype(str).str.replace("-", "", regex=True)

# Add a 'Company' column to match 'sa_company_name'
df['Company'] = df['sa_company_name']

# Display first few rows
print(df_excel.head())
display(df)

pd.set_option('display.max_rows', None)

  Transaction Date                                            Company  Column1
0         20171122                   34 Cross Systems Private Limited        1
1         20151024                  360 One Wam Limited (NSEI:360ONE)        1
2         20050218         63 moons technologies limited (BSE:526881)        1
3         20200612  91Streets Media Technologies/Ascent Health/API...        1
4         20100601                                 9X Media Pvt. Ltd.        1

,xsa_finance1_cocode,sa_company_name,sa_finance1_year,sa_ann_rep_months,sa_fs_format,sa_total_income,sa_compensation_to_employees,sa_pat,sa_total_assets,sa_cf_direct_taxes_paid,sa_no_of_employees,company_name,co_industry_gp_code,co_industry_name,Company
0,3,'K' STEAMSHIP AGENCIES PVT. LTD.,20010331,12,IGAAP,0.6842,0.1394,0.1351,3.7087,NaN,NaN,'K' STEAMSHIP AGENCIES PVT. LTD.,1.100000e+14,Diversified,'K' STEAMSHIP AGENCIES PVT. LTD.
1,3,'K' STEAMSHIP AGENCIES PVT. LTD.,20020331,12,IGAAP,1.7645,0.1498,0.5437,3.2356,NaN,NaN,'K' STEAMSHIP AGENCIES PVT. LTD.,1.100000e+14,Diversified,'K' STEAMSHIP AGENCIES PVT. LTD.
2,3,'K' STEAMSHIP AGENCIES PVT. LTD.,20030331,12,IGAAP,1.8660,0.2645,0.5478,5.1027,NaN,NaN,'K' STEAMSHIP AGENCIES PVT. LTD.,1.100000e+14,Diversified,'K' STEAMSHIP AGENCIES PVT. LTD.
3,3,'K' STEAMSHIP AGENCIES PVT. LTD.,20040331,12,IGAAP,2.5436,0.3310,0.9130,6.9755,NaN,NaN,'K' STEAMSHIP AGENCIES PVT. LTD.,1.100000e+14,Diversified,'K' STEAMSHIP AGENCIES PVT. LTD.
4,3,'K' STEAMSHIP AGENCIES PVT. LTD.,20110331,12,IGAAP,8.4020,1.3314,2.5095,13.2364,NaN,NaN,'K' STEAMSHIP AGENCIES PVT. LTD.,1.100000e+14,Diversified,'K' STEAMSHIP AGENCIES PVT. LTD.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
684801,713703,A D F TRADING PVT. LTD.,20200331,12,IGAAP,1.8009,0.0336,0.0148,0.5030,NaN,NaN,A D F TRADING PVT. LTD.,1.010404e+14,Wholesale trading,A D F TRADING PVT. LTD.
684802,713703,A D F TRADING PVT. LTD.,20210331,12,IGAAP,2.0400,0.0302,0.0014,0.5097,NaN,NaN,A D F TRADING PVT. LTD.,1.010404e+14,Wholesale trading,A D F TRADING PVT. LTD.
684803,713703,A D F TRADING PVT. LTD.,20220331,12,IGAAP,2.5641,0.0249,0.0052,0.4118,NaN,NaN,A D F TRADING PVT. LTD.,1.010404e+14,Wholesale trading,A D F TRADING PVT. LTD.
684804,713703,A D F TRADING PVT. LTD.,20230331,12,IGAAP,1.9014,0.0304,0.0012,0.5492,NaN,NaN,A D F TRADING PVT. LTD.,1.010404e+14,Wholesale trading,A D F TRADING PVT. LTD.
684805,713703,A D F TRADING PVT. LTD.,20240331,12,IGAAP,1.6134,0.0229,0.0036,0.5374,NaN,NaN,A D F TRADING PVT. LTD.,1.010404e+14,Wholesale trading,A D F TRADING PVT. LTD.

Warning: total number of rows (684806) exceeds max_rows (20000). Limiting to first (20000) rows.